// ACTION TYPES
const CREATE_TABLE = "CREATE_TABLE";
const ADD_ROW = "ADD_ROW";
const ADD_COLUMN = "ADD_COLUMN";
const SELECT_COLOR = "SELECT_COLOR";

export default { CREATE_TABLE, ADD_ROW, ADD_COLUMN, SELECT_COLOR }